name: Pipeline C Calculator
on: push

jobs:
  Compilation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Compilation
        run: |
          mkdir -p build
          cd build
          cmake ..
          make
      - name: Upload executable
        uses: actions/upload-artifact@v4
        with:
          name: calculator-exe
          path: build/src/calculator

  Test_Add:
    runs-on: ubuntu-latest
    needs: Compilation
    steps:
      - name: Download executable
        uses: actions/download-artifact@v4
        with:
          name: calculator-exe
          path: ./build/src
      - name: Test add
        run: ./build/src/calculator add 10 5

  Test_Sub:
    runs-on: ubuntu-latest
    needs: Compilation
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: calculator-exe
          path: ./build/src
      - name: Test sub
        run: ./build/src/calculator sub 3 -2

  Test_Mul:
    runs-on: ubuntu-latest
    needs: Compilation
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: calculator-exe
          path: ./build/src
      - name: Test mul
        run: ./build/src/calculator mul 5 5

  Test_Div:
    runs-on: ubuntu-latest
    needs: Compilation
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: calculator-exe
          path: ./build/src
      - name: Test div
        run: ./build/src/calculator div 1 5

  Test_Car:
    runs-on: ubuntu-latest
    needs: Compilation
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: calculator-exe
          path: ./build/src
      - name: Test car
        run: ./build/src/calculator car 5

  Deploy:
    runs-on: ubuntu-latest
    needs: [Test_Add, Test_Sub, Test_Mul, Test_Div, Test_Car]
    steps:
      - name: Déploiement
        run: echo "Déploiement de la solution"
