name: Pipeline C Calculator
on: push

jobs:
  Compilation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3   # Git clone automatiquement
      - name: Compilation
        run: |
          mkdir build
          cd build
          cmake ..
          make

  Test_Add:
    runs-on: ubuntu-latest
    needs: Compilation
    steps:
      - name: Test add
        run: |
          cd build
          ./src/calculator add 10 5

  Test_Sub:
    runs-on: ubuntu-latest
    needs: Compilation
    steps:
      - name: Test sub
        run: |
          cd build
          ./src/calculator sub 3 -2

  Test_Mul:
    runs-on: ubuntu-latest
    needs: Compilation
    steps:
      - name: Test mul
        run: |
          cd build
          ./src/calculator mul 5 5

  Test_Div:
    runs-on: ubuntu-latest
    needs: Compilation
    steps:
      - name: Test div
        run: |
          cd build
          ./src/calculator div 1 5

  Test_Car:
    runs-on: ubuntu-latest
    needs: Compilation
    steps:
      - name: Test car
        run: |
          cd build
          ./src/calculator car 5

  Deploy:
    runs-on: ubuntu-latest
    needs: [Test_Add, Test_Sub, Test_Mul, Test_Div, Test_Car]
    steps:
      - name: Déploiement
        run: echo "Déploiement de la solution"
